version: '3.5'

services:
  postgres:
    container_name: nest_project_postgres_container
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-nest_primary_db}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-xyz9900}
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

 
networks:
  postgres:
    driver: bridge

volumes:
    postgres: